export const GET_ALL_TODO = 'GET_ALL_TODO'
export const ADD_NEW_TODO = 'ADD_NEW_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const EDIT_POST = 'EDIT_POST'
